# Generated by Django 4.2.11 on 2024-04-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('category', models.IntegerField(choices=[(0, 'Beach'), (1, 'History'), (3, 'City')], default=0)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (0, 'Published')], default=0)),
            ],
        ),
    ]
