# Generated by Django 4.2.11 on 2024-05-26 01:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='cover image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='detail_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='detail image'),
        ),
    ]
