# Generated by Django 4.2.11 on 2024-04-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-comment_date']},
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.IntegerField(choices=[(0, 'Beach'), (1, 'History'), (2, 'City')], default=0),
        ),
    ]
