# Generated by Django 4.2.11 on 2024-04-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_reviews_options_article_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
