# Generated by Django 4.2.11 on 2024-05-12 11:44

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_article_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='detail_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_article', to='home.article'),
        ),
    ]
